# configs/movenet.yaml

# 复现/日志
seed: 42
deterministic: false        # 需要严格可复现就设 true（会稍慢）
verbose: true               # （可选）若你的 trainer 支持

# 训练恢复 / 预加载
resume: true           

# -----------------------------
# 模型
# -----------------------------
model:
  class: movenet            # alias -> sparrow.models.movenet.MoveNet
  args:
    backbone: shufflenet_v2   # ← 从 JSON 的 shufflenet_v2
    width_mult: 1.5           # ← JSON
    num_joints: 17            # ← JSON task_params.num_joints
    neck_outc: 96             # ← JSON（模型若需要就会吃到）
    head_midc: 48             # ← JSON（模型若需要就会吃到）

  # class: movenet
  # args:
  #   backbone: mobilenet_v3
  #   width_mult: 1.0
  #   num_joints: 17
  #   neck_outc: 64
  #   head_midc: 32

# -----------------------------
# 训练器
# -----------------------------
trainer:
  class: kpts_trainer
  args:
    epochs: 200
    save_dir: output/movenet
    img_size: 192

    # 优化器
    optimizer_cfg:
      optimizer_name: adam
      learning_rate: 0.00035
      weight_decay: 0.0001

    # 学习率调度
    scheduler_cfg:
      scheduler_name: MultiStepLR
      milestones: [90, 130]
      gamma: 0.2
      # 可选：其它调度器用到的明参举例
      # step_size: 30         # StepLR
      # T_0: 10               # CosineAnnealingWarmRestarts
      # T_mult: 2
      # mode: min             # ReduceLROnPlateau
      # factor: 0.5
      # patience: 5
      # min_lr: 1.0e-6

    # 训练技巧
    training_params:
      use_amp: true
      use_ema: true
      ema_decay: 0.9998
      clip_grad_norm: 1.0   # ← 注意别再用 clip_gradient
      log_interval: 10


# -----------------------------
# 数据
# -----------------------------
data:
  train:
    builder: coco_kpts_dataloader      # alias -> sparrow.datasets.coco_kpts.create_kpts_dataloader
    args:
      dataset_root: ./data/coco2017_movenet   # ← JSON dataset_root_path
      img_size: 192
      target_stride: 4
      batch_size: 64                   # ← JSON
      num_workers: 8                   # ← JSON
      pin_memory: true                 # ← JSON
      is_train: true
      aug_cfg:                         # ← JSON 的增强/监督参数全部转到这里
        use_color_aug: true
        use_flip: true
        use_rotate: true
        rotate_deg: 12.0
        use_scale: true
        scale_range: [0.6, 1.25]
        gaussian_radius: 2
        sigma_scale: 1.0
        # 下面几个是新数据集实现支持的（可选，不写走默认）
        # use_dynamic_radius: true
        # kpt_radius_factor: 0.025
        # ctr_radius_factor: 0.035
        # min_radius: 1

  val:
    builder: coco_kpts_dataloader
    args:
      dataset_root: ./data/coco2017_movenet
      img_size: 192
      target_stride: 4
      batch_size: 64
      num_workers: 4
      pin_memory: true
      is_train: false
      aug_cfg: {}                      # 验证集默认关闭增强，半径策略已在实现里处理


# -----------------------------
# 导出
# -----------------------------
export:
  format: onnx
  output: output/movenet/movenet.onnx
  opset: 13
  input:
    shape: [1, 3, 192, 192]
  wrapper:
    class: dummy_movenet
    args:
      num_joints: 17
      img_size: 192
      target_stride: 4