# configs/reidlite.yaml

# 复现/日志
seed: 42
deterministic: false        # 需要严格可复现就设 true（会稍慢）
verbose: true               # （可选）若你的 trainer 支持

# 训练恢复 / 预加载
resume: true

# 模型参数
model:
  class: reidlite           # 模型名称
  args:
    backbone: mobilenet_v3  # 可使用mobilenet_v2, mobilenet_v3, shufflenet_v2
    width_mult: 0.5
    emb_dim: 128

trainer:
  class: reid_trainer

  args:
    epochs: 60
    save_dir: outputs/reidlite
    img_h: 256
    img_w: 128
    num_classes: 1594
    id_head: cosface
    w_id: 1.0
    w_tri: 1.0
    triplet_margin: 0.3
    label_smooth_eps: 0.1
    main_metric:  cmc@1         # 主指标： 若切换为 'loss'，请把 mode 也改为 'min'
    mode: max

    optimizer_cfg:
      optimizer_name: AdamW
      learning_rate: 3e-4
      weight_decay: 1e-4

    scheduler_cfg:
      scheduler_name: MultiStepLR
      milestones: [20, 40, 55]
      gamma: 0.2

    training_params:
      use_amp: true
      use_ema: true
      ema_decay: 0.9998
      clip_grad_norm: 0.0
      log_interval: 10

      debug_grad_flow: true     # 开启监控
      debug_grad_every: 50      # 每隔多少个 iteration 打印一次


data:
  train:
    builder: reid_dataloader
    args:
      csv_path: data/reid/final_pairs.csv
      root_dir: data/reid
      batch_size: 64
      num_instances: 4
      num_workers: 8
      img_h: 256
      img_w: 128
      is_train: true

  val:
    builder: reid_dataloader
    args:
      csv_path: data/reid/final_pairs.csv
      root_dir: data/reid
      batch_size: 64
      num_instances: 4
      num_workers: 8
      img_h: 256
      img_w: 128
      is_train: false
